### ISSUE TITLE
Device image not updating

### ISSUE THREAD

**Issue by brec9824** [uidaho/smartsettia#59]
Just was looking at the test unit and the image is stuck at 3:57am even though it is 10:14am. Double checked and the browser is not using a cached image so either the device isn't sending a new image or the server isn't saving the image.

**Comment by brandonjank** [comment]
looks like the school's DNS servers did something unexpected and python requests blew up:
```
2017-10-07 03:57:04: api/update success
--- Opening /dev/video0...
Trying source module v4l2...
/dev/video0 opened.
No input was specified, using the first.
--- Capturing frame...
Skipping 3 frames...
Capturing 1 frames...
Captured 4 frames in 0.35 seconds. (11 fps)
--- Processing captured image...
Setting output format to JPEG, quality 95
Setting title "engr-smartsettia-test".
Setting subtitle "cpu: 44.9 C".
Setting info text "22cb95fc-94b6-510d-b08c-be4b96c017b0".
2017-10-07 03:57:15: api/update success
Writing JPEG image to '/cameratmp/camera.jpg'.
2017-10-07 03:57:16: api/image success
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x76279430>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.4/dist-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='smartsettia.com', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x76279430>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fakedevice.py", line 182, in <module>
    schedule.run_pending()
  File "/usr/local/lib/python3.4/dist-packages/schedule/__init__.py", line 452, in run_pending
    default_scheduler.run_pending()
  File "/usr/local/lib/python3.4/dist-packages/schedule/__init__.py", line 75, in run_pending
    self._run_job(job)
  File "/usr/local/lib/python3.4/dist-packages/schedule/__init__.py", line 129, in _run_job
    ret = job.run()
  File "/usr/local/lib/python3.4/dist-packages/schedule/__init__.py", line 377, in run
    ret = self.job_func()
  File "./fakedevice.py", line 92, in api_update_job
    response = requests.post(url, json=data, headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='smartsettia.com', port=443): Max retries exceeded with url: /api/update (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x76279430>: Failed to establish a new connection: [Errno -2] Name or service not known',))
pi@raspberrypi:~ $
```
